### ISSUE TITLE
Grant access on RabbitMQ to MyMircoService

### ISSUE THREAD

**Issue by FrancoisT31** [FrancoisT31/ml-managed-issues#1]
The MyMicroService need to pick-up data from the RabbitMQ cluster on staging env.

**Comment by FrancoisT31** [comment]
Don't forget RMQ is lb with haproxy

**Comment by FrancoisT31** [comment]
<ML> Hi,
I found following results on my base. Please check the box if they are relevant.
- [ ] Doc: http://documentation.people-doc.com/sre/services/rabbitmq.html
- [ ] Doc: http://documentation.people-doc.com/sre/services/haproxy.html
- [ ] Doc: http://documentation.people-doc.com/sre/procedures/deploy-micro-service.html
- [ ] Issue: #1234 : Firewall need to be restarted on load-balancer
- [ ] Issue: #1235 : Routing error on rmq staging
- [ ] PR: #4567 : Update playbook to setup security groups
